[package]
name = "fixed-vectors"
version = "1.2.2"
edition = "2018"
readme = "README.MD"
repository = "https://github.com/c1m50c/fixed-vectors"
license = "MIT"
description = "Library implementing fixed-length Vectors meant for representing dimensional values."
keywords = [
    "math", "vector", "fixed-length", "fixed-vectors", "vector2", "vector3", "vector4", "macros", "macro",
    "game-dev", "4d", "3d", "2d"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"

[lib]
doctest = false