[package]
name = "fixed-vectors"
version = "1.2.4"
edition = "2018"
readme = "README.MD"
repository = "https://github.com/c1m50c/fixed-vectors"
license = "MIT"
description = "Library implementing fixed-length Vectors meant for representing dimensional values."
keywords = [ "math", "vector", "vector2", "vector3", "vector4" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"

[lib]
doctest = false