[package]
name = "fixed-vectors"
version = "2.0.4"
edition = "2021"
readme = "README.MD"
repository = "https://github.com/c1m50c/fixed-vectors"
license = "MIT"
description = "Library implementing fixed-length Vectors meant for representing dimensional values."
keywords = [ "math", "vector", "vector2", "vector3", "gamedev" ]
categories = [ "data-structures", "game-development", "mathematics" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"

[features]
macros = [  ]