name: Publish

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          cargo test --verbose
      
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO }}
        run: |
          cargo login
          cargo publish --all-features
        continue-on-error: true # For the case the version is already uploaded.