name: Publish

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish - `crates.io`
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2

      - name: Publish - `crates.io`
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo login
          cargo publish --all-features --verbose
        continue-on-error: true # For the case the version is already uploaded.